## File generated by the BNF Converter (bnfc 2.9.3).

CXX=clang++
CXXFLAGS=-g -std=c++17 -Wall -pedantic

FLEX=flex
FLEX_OPTS=-Pinstant_

BISON=bison
BISON_OPTS=-t -pinstant_

OBJS=src/Absyn.o src/Buffer.o src/Lexer.o src/Parser.o

.PHONY : clean distclean

all : Compiler

clean :
	rm Compiler; rm -f *.o; cd src; rm -f *.o instant.aux instant.log instant.pdf instant.dvi instant.ps instant

distclean : clean
	cd src; rm -f Absyn.C Absyn.H Buffer.C Buffer.H Bison.H Parser.C Parser.H ParserError.H instant.y Lexer.C instant.l Skeleton.C Skeleton.H Makefile instant.tex

Compiler : ${OBJS} src/Main.o
	@echo "Linking Compiler..."
	${CXX} ${OBJS} src/Main.o -o Compiler; chmod u+x+w+r insc_llvm; chmod u+x+w+r insc_jvm;

Absyn.o : src/Absyn.C src/Absyn.H
	${CXX} ${CXXFLAGS} -c Absyn.C

Buffer.o : src/Buffer.C src/Buffer.H
	${CXX} ${CXXFLAGS} -c Buffer.C

Lexer.C : src/instant.l
	${FLEX} ${FLEX_OPTS} -oLexer.C instant.l

Parser.C Bison.H : src/instant.y
	${BISON} ${BISON_OPTS} instant.y -o Parser.C

Lexer.o : src/Lexer.C src/Bison.H
	${CXX} ${CXXFLAGS} -c Lexer.C

Parser.o : src/Parser.C src/Absyn.H src/Bison.H
	${CXX} ${CXXFLAGS} -c Parser.C

Skeleton.o : src/Skeleton.C src/Skeleton.H src/Absyn.H
	${CXX} ${CXXFLAGS} -Wno-unused-parameter -c Skeleton.C

LLVM_Compiler.o : src/LLVM_Compiler.cpp
	${CXX} ${CXXFLAGS} -Wno-unused-parameter -c LLVM_Compiler.C

JVM_Compiler.o : src/JVM_Compiler.cpp
	${CXX} ${CXXFLAGS} -Wno-unused-parameter -c JVM_Compiler.C

Main.o : src/Main.cpp src/Parser.H src/Absyn.H src/LLVM_Compiler.cpp src/JVM_Compiler.cpp
	${CXX} ${CXXFLAGS} -c src/Main.cpp
