## File generated by the BNF Converter (bnfc 2.9.3).

CC=g++ -g
CCFLAGS=--ansi -W -Wall -Wno-unused-parameter -Wno-unused-function -Wno-unneeded-internal-declaration

FLEX=flex
FLEX_OPTS=-Pinstant_

BISON=bison
BISON_OPTS=-t -pinstant_

OBJS=src/Absyn.o src/Buffer.o src/Lexer.o src/Parser.o src/Printer.o

.PHONY : clean distclean

all : Compiler

clean :
	rm -f *.o Testinstant; cd src; rm -f *.o instant.aux instant.log instant.pdf instant.dvi instant.ps instant

distclean : clean
	cd src; rm -f Absyn.C Absyn.H Buffer.C Buffer.H Test.C Bison.H Parser.C Parser.H ParserError.H instant.y Lexer.C instant.l Skeleton.C Skeleton.H Printer.C Printer.H Makefile instant.tex

Testinstant : ${OBJS} src/Test.o
	@echo "Linking Testinstant..."
	${CC} ${OBJS} src/Test.o -o Testinstant

Compiler : ${OBJS} src/Main.o
	@echo "Linking Compiler..."
	${CC} ${OBJS} src/Main.o -o Compiler

Absyn.o : src/Absyn.C src/Absyn.H
	${CC} ${CCFLAGS} -c Absyn.C

Buffer.o : src/Buffer.C src/Buffer.H
	${CC} ${CCFLAGS} -c Buffer.C

Lexer.C : src/instant.l
	${FLEX} ${FLEX_OPTS} -oLexer.C instant.l

Parser.C Bison.H : src/instant.y
	${BISON} ${BISON_OPTS} instant.y -o Parser.C

Lexer.o : src/Lexer.C src/Bison.H
	${CC} ${CCFLAGS} -c Lexer.C

Parser.o : src/Parser.C src/Absyn.H src/Bison.H
	${CC} ${CCFLAGS} -c Parser.C

Printer.o : src/Printer.C src/Printer.H src/Absyn.H
	${CC} ${CCFLAGS} -c Printer.C

Skeleton.o : src/Skeleton.C src/Skeleton.H src/Absyn.H
	${CC} ${CCFLAGS} -Wno-unused-parameter -c Skeleton.C

LLVM_Compiler.o : src/LLVM_Compiler.cpp
	${CC} ${CCFLAGS} -Wno-unused-parameter -c LLVM_Compiler.C

JVM_Compiler.o : src/JVM_Compiler.cpp
	${CC} ${CCFLAGS} -Wno-unused-parameter -c JVM_Compiler.C

Test.o : src/Test.C src/Parser.H src/Printer.H src/Absyn.H
	${CC} ${CCFLAGS} -c src/Test.C

Main.o : src/Main.cpp src/Parser.H src/Printer.H src/Absyn.H src/LLVM_Compiler.cpp src/JVM_Compiler.cpp
	${CC} ${CCFLAGS} -c src/Main.cpp
